### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by vgeorge**
Changelog:

- Add `disclaimer` property to model

A complete release note will be done when [milestone v1.0.0](https://github.com/global-electrification-platform/data-service/milestone/1) is finished.

@EricSoroos this deploy also depends on a migration. I'll merge when you approve the PR.

### CODE REVIEW

**Comment by EricSoroos** [comment]
So the migration is:
```
alter table models add column disclaimer text;
```

**Comment by vgeorge** [comment]
@EricSoroos yes, that's correct.

**Comment by vgeorge** [comment]
@EricSoroos If the migration has been applied, can you please approve this PR so I can merge? I added a commit bumping the version from `v1.0.0-rc2` to `v1.0.0` as this is has already being used in production.

**Comment by EricSoroos** [comment]
I've added the migration in production.

**Pull request merged**
