### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by vgeorge**
# Changelog

List of updates from release [v1.0.0-rc1](https://github.com/global-electrification-platform/data-service/releases/tag/v1.0.0-rc1):

## 🎉 Features

No features added.

## 🚀 Improvements

- Store compressed responses at Redis cache #81
- Add `sourceData` property to models #86
- Include all steps in investment cost summaries #88

## 🐛 Fixes

No fixes added.

# Notes 

- ⚠️ **This release includes a migration that adds column `sourceData` to `models` table, the server won't run without it** 
- Issue #76 "Data Service should handle retries" is not ready and will be deployed in a minor release when complete
- @EricSoroos I'm marking you as a reviewer, please set this PR to approved when production server is ready to receive it or let me know if you need any change

### CODE REVIEW

**Comment by EricSoroos** [comment]
From a deployment POV, we need to:

* add the column to the database. The Dataservice has a read-only connection, so it will fail to do the migration. This is a safe migration WRT backwards compatibility, so we should do this before the update. I don't see any data for the models added in the sourceData migration, so I assume it's just a matter of: ` alter table models add column sourceData (json); ` (or jsonb?)
* Bump up the node version on the EB environment. Is there anything here that specifically requires either version of node?
* Dump the existing redis cache, because we're assuming that anything in the redis cache is compressed.

**Comment by vgeorge** [comment]
Hey @EricSoroos, please check my comments below.

## Migration

The data service doesn't do the migraton on deploy, it has to be done in separate via command line like this:

    PG_CONNECTION_STRING='connection string' node_modules/.bin/knex migrate:latest

If you really need to do it manually, I believe the steps needed are:

- `alter table models add column sourceData (json);`
- Include record in `knex_migrations` table to not break future migrations:


| id    | name      | batch| migration_time  |
| ------------- |-------------| -----|-----|
14|"20190923105526_add-model-source-data.js"|2|"2019-11-11 11:10:43.992+00"

This record I just copied from my local env, I'm not sure what the column `batch` does.

## Node version

I'm not if I understood. Is the EB instance is running Node.js 10+ the deploy should be fine.

## Dump Redis

Yes, it would be good to dump all cache.

**Comment by EricSoroos** [comment]
I think I need to do the migration manually, because to run it manually, I'd have to have access to the new app on a machine I can ssh to. It's just easier to insert. 
* Current Node on EB is 8.16.1, I'll update that.

**Comment by vgeorge** [comment]
@EricSoroos please let me know when you finish the steps and I'll merge this.

**Comment by EricSoroos** [comment]
```gep=> rollback;begin;
ROLLBACK
BEGIN
gep=> alter table models add column sourceData json;
ALTER TABLE
gep=> insert into knex_migrations(name, batch, migration_time) values ('20190923105526_add-model-source-data.js', 11, now());
INSERT 0 1
gep=> select * from knex_migrations;
 id |                         name                          | batch |        migration_time         
----+-------------------------------------------------------+-------+-------------------------------
  1 | 20181029115757_add-countries.js                       |     1 | 2018-11-29 11:46:18.562+00
  2 | 20181106112819_add-models.js                          |     1 | 2018-11-29 11:46:18.59+00
  3 | 20181107110836_add-scenarios.js                       |     1 | 2018-11-29 11:46:18.628+00
  4 | 20181126115545_change-scenario-column-name.js         |     2 | 2018-11-30 10:46:37.727+00
  5 | 20181130141626_add-country-to-models.js               |     3 | 2018-11-30 14:20:31.518+00
 38 | 20181203134634_add-type-to-model.js                   |     4 | 2018-12-03 13:47:17.633+00
 39 | 20181204162054_rename-filter-values-column.js         |     5 | 2018-12-04 18:09:43.43+00
 40 | 20181211171505_rename-area-to-feature.js              |     6 | 2018-12-13 16:51:48.983+00
 41 | 20181211181807_change-etype-type.js                   |     6 | 2018-12-13 16:51:49.045+00
 42 | 20181219143137_add_modelid_to_scenarios.js            |     7 | 2018-12-19 14:33:46.719+00
 45 | 20190103163855_add_timesteps_to_models.js             |     8 | 2019-01-03 16:49:36.858+00
 46 | 20190104111513_create_single_col_for_summary_props.js |     9 | 2019-01-04 11:28:38.666+00
 47 | 20190819123220_add-model-base-year.js                 |    10 | 2019-08-30 14:16:51.527+00
 48 | 20190923105526_add-model-source-data.js               |    11 | 2019-11-13 15:48:26.910838+00
(14 rows)

gep=> \d models;
                         Table "public.models"
   Column    |          Type          | Collation | Nullable | Default 
-------------+------------------------+-----------+----------+---------
 id          | character varying(255) |           | not null | 
 updatedAt   | date                   |           |          | 
 attribution | json                   |           |          | 
 levers      | json[]                 |           |          | 
 filters     | json[]                 |           |          | 
 map         | json                   |           |          | 
 name        | character varying(255) |           |          | 
 version     | character varying(255) |           |          | 
 description | text                   |           |          | 
 country     | character varying(2)   |           |          | 
 type        | character varying(15)  |           |          | 
 timesteps   | json[]                 |           |          | 
 baseYear    | integer                |           | not null | 
 sourcedata  | json                   |           |          | 
Indexes:
    "models_pkey" PRIMARY KEY, btree (id)

gep=> commit;
COMMIT
gep=> 
```

**Comment by EricSoroos** [comment]
Oops, your case sensitivity strikes.

**Comment by EricSoroos** [comment]
@vgeorge Go ahead and merge, I'll dump the redis cache when EB refreshes.

**Comment by EricSoroos** [comment]
Redis cache has been dumped, also performing redis essential update at the same time.

**Pull request merged**
